name: 'API testing using'
description: 'Run API tests for Google APIs using Karate Framework and GitHub Action for CI-CD'
inputs:
  url:
    description: "URL to pass as script variable to test."
    required: false
  tests:
    description: 'Karata file or directory path with tests.'
    required: true
runs:
  using: docker
  image: Dockerfile